eithon:
  UseMarkUpForMessages: 1
  UseWrappingForMessages: 0
  
  #
  # Debug level
  #  0 = NONE (no debug messages)
  #  1 = MAJOR (only major messages)
  #  2 = MINOR (also minor messages)
  #  3 = VERBOSE (all messages)
  #
  DebugLevel: 3

MaxAllowedTeleportDelayTimeSpan: 30
MaxAllowedMessageDelayInSeconds: 10

#
# The warp locations are read from the database on a regular basis to make sure that we have the latest data.
# This is how often that should happen.
#
ReloadWarpLocationsAfterTimeSpan: 5m

GroupPriorities: [Owner, Admin, Developer, Architect, Designer, Mod, Submod, Tourist, Trusted, Vip1, Vip2, Vip3, Builder, Legendary, Veteran, Citizen, Member, New, Funder, Founder, RetiredAdmin, RetiredArchitect, RetiredMod]

#
# The primary server (from a BungeeChord perspective)
PrimaryBungeeServer: Hub

database:
  Name: eithon_bungee
  Hostname: localhost
  Port: 3306
  Username: eithon_plugin
  Password: 94SnHAGP3RV0mESN

# TST
#  Name: TST_e_bungee
#  Hostname: rookgard.eithon.net
#  Port: 3307
#  Username: TST_e_plugin
#  Password: bWfRHZsAy42RdFBJ

# DEV
#  Name: DEV_e_bungee
#  Hostname: rookgard.eithon.net
#  Port: 3307
#  Username: DEV_e_plugin
#  Password: J5FE9EFCD1GX8tjg

commands:

messages:
  #
  # Parameters: <player name> (%s)
  #
  RequestTpTo: 'Player %s requests to teleport to you. Enter one of the commands "/eithonbungee tp accept" or "/eithonbungee tp deny".'
  
  #
  # Parameters: <player name> (%s)
  #
  RequestTpHere: 'Player %s requests to teleport you to him/her. Enter one of the commands "/eithonbungee tp accept" or "/eithonbungee tp deny".'
  
  #
  # Parameters: <player name> (%s)
  #
  DenyTpTo: 'Player %s denied you to teleport to him/her.'
  
  #
  # Parameters: <player name> (%s)
  #
  DenyTpHere: 'Player %s denied to be teleported to you.'
  
  #
  # Parameters: <player name> (%s), <message> (%s)
  #
  MessageSent: 'To %s: %s'
  
  #
  # Parameters: <player name> (%s), <message> (%s)
  #
  MessageFrom: 'From %s: %s'
  
  #
  # Parameters: <name> (%s)
  #
  WarpAdded: 'Warp location %s has been added.'

  #
  # Parameters: <server name> (%s)
  AlreadyConnectedToServer: You are already connected to server %s.

  #
  # Parameters: <server name> (%s), <error message> (%s)
  CouldNotConnectToServer: "Could not connect to server %s: %s"

  #
  # Parameters: <server name> (%s)
  ConnectedToServer: Connected to server %s.

  #
  # Parameters: -
  TryAgain: Could not execute the command properly now. Please try again.
  
  #
  # This message is broadcasted when someone logs in to the server for the first time
  # Parameters: <player name> (%s)
  #
  JoinedServerFirstTime: "[color=green]+ [/color][color=lightpurple]%s[/color] [color=darkaqua]joined for the first time![/color]"

  #
  # This message is broadcasted to members with rankup
  # Parameters: <player name> (%s)
  #
  PleaseWelcomeNewPlayer: "[subtitle/]Welcome [color=lightpurple]%s[/color] [color=white]to the server![/color]"
  
  #
  # Confirmation message when banning a player
  # Parameters: <player name> (%s), <server name> (%s), <time> (%s)
  #
  BannedPlayer: "Player %s is now banned on server %s until %s."
  
  #
  # Confirmation message when removing the ban for a player
  # Parameters: <player name> (%s), <server name> (%s) 
  #
  UnbannedPlayer: "Player %s has been unbanned on server %s."
  
  #
  # Trying to unban a player that wasn't banned
  # Parameters: <player name> (%s), <server name> (%s) 
  #
  PlayerNotBanned: "Player %s is not banned on server %s?"
  
  #
  # %PLAYER_NAME%, %SERVER_NAME%
  #
  join:
    message: '[color=green]+[/color] [color=yellow]%PLAYER_NAME%[/color] [color=gray]has joined the %SERVER_NAME% server.[/color]'
    groups:
        Owner: '[color=green]+[/color] [color=red]%PLAYER_NAME%[/color] [color=gray]has joined the %SERVER_NAME% server.[/color]'
        Admin: '[color=green]+[/color] [color=red]%PLAYER_NAME%[/color] [color=gray]has joined the %SERVER_NAME% server.[/color]'
        Developer: '[color=green]+[/color] [color=darkpurple]%PLAYER_NAME%[/color] [color=gray]has joined the %SERVER_NAME% server.[/color]'
        Architect: '[color=green]+[/color] [color=aqua]%PLAYER_NAME%[/color] [color=gray]has joined the %SERVER_NAME% server.[/color]'
        Designer: '[color=green]+[/color] [color=darkaqua]%PLAYER_NAME%[/color] [color=gray]has joined the %SERVER_NAME% server.[/color]'
        Mod: '[color=green]+[/color] [color=green]%PLAYER_NAME%[/color] [color=gray]has joined the %SERVER_NAME% server.[/color]'
        Submod: '[color=green]+[/color] [color=darkgreen]%PLAYER_NAME%[/color] [color=gray]has joined the %SERVER_NAME% server.[/color]'
        Tourist: '[color=green]+[/color] [color=yellow]%PLAYER_NAME%[/color] [color=gray]has joined the %SERVER_NAME% server.[/color]'
        Trusted: '[color=green]+[/color] [color=yellow]%PLAYER_NAME%[/color] [color=gray]has joined the %SERVER_NAME% server.[/color]'
        Builder: '[color=green]+[/color] [color=yellow]%PLAYER_NAME%[/color] [color=gray]has joined the %SERVER_NAME% server.[/color]'
        Legend: '[color=green]+[/color] [color=yellow]%PLAYER_NAME%[/color] [color=gray]has joined the %SERVER_NAME% server.[/color]'
        Veteran: '[color=green]+[/color] [color=blue]%PLAYER_NAME%[/color] [color=gray]has joined the %SERVER_NAME% server.[/color]'
        Citizen: '[color=green]+[/color] [color=blue]%PLAYER_NAME%[/color] [color=gray]has joined the %SERVER_NAME% server.[/color]'
        Member: '[color=green]+[/color] [color=blue]%PLAYER_NAME%[/color] [color=gray]has joined the %SERVER_NAME% server.[/color]'
        New: '[color=green]+[/color] [color=lightpurple]%PLAYER_NAME%[/color] [color=gray]has joined the %SERVER_NAME% server.[/color]'
        Guest: '[color=green]+[/color] [color=lightpurple]%PLAYER_NAME%[/color] [color=gray]has joined the %SERVER_NAME% server.[/color]'
        Vip1: '[color=green]+[/color] [color=gold]%PLAYER_NAME%[/color] [color=gray]has joined the %SERVER_NAME% server.[/color]'
        Vip2: '[color=green]+[/color] [color=gold]%PLAYER_NAME%[/color] [color=gray]has joined the %SERVER_NAME% server.[/color]'
        Vip3: '[color=green]+[/color] [color=gold]%PLAYER_NAME%[/color] [color=gray]has joined the %SERVER_NAME% server.[/color]'
        Funder: '[color=green]+[/color] [color=gold]%PLAYER_NAME%[/color] [color=gray]has joined the %SERVER_NAME% server.[/color]'
        Founder: '[color=green]+[/color] [color=yellow]%PLAYER_NAME%[/color] [color=gray]has joined the %SERVER_NAME% server.[/color]'
        RetiredAdmin: '[color=green]+[/color] [color=gold]%PLAYER_NAME%[/color] [color=gray]has joined the %SERVER_NAME% server.[/color]'
        RetiredArchitect: '[color=green]+[/color] [color=gold]%PLAYER_NAME%[/color] [color=gray]has joined the %SERVER_NAME% server.[/color]'
        RetiredMod: '[color=green]+[/color] [color=gold]%PLAYER_NAME%[/color] [color=gray]has joined the %SERVER_NAME% server.[/color]'
    players:
        Addos: '[color=green]+[/color] [color=gray]Yo yo yo, Master[/color] [color=gold]%PLAYER_NAME%[/color] [color=gray]is in the %SERVER_NAME% house![/color]'
        Kyralix: '[color=green]+[/color] [color=gold]%PLAYER_NAME%[/color] [color=gray]the cool kid just joined the %SERVER_NAME% server! Yay ~[/color]'
        Robot_Rebel: '[color=green]+[/color] [color=darkgreen]%PLAYER_NAME%[/color] [color=gray]just joined the %SERVER_NAME% server. Hello Bootifuls![/color]'
  quit:
    message: '[color=red]-[/color] [color=yellow]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
    groups:
        Owner: '[color=red]-[/color] [color=red]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
        Admin: '[color=red]-[/color] [color=red]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
        Developer: '[color=red]-[/color] [color=darkpurple]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
        Architect: '[color=red]-[/color] [color=aqua]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
        Designer: '[color=red]-[/color] [color=darkaqua]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
        Mod: '[color=red]-[/color] [color=green]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
        Submod: '[color=red]-[/color] [color=darkgreen]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
        Tourist: '[color=red]-[/color] [color=yellow]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
        Trusted: '[color=red]-[/color] [color=yellow]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
        BuilderT1: '[color=red]-[/color] [color=yellow]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
        BuilderT2: '[color=red]-[/color] [color=yellow]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
        Legend: '[color=red]-[/color] [color=yellow]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
        Veteran: '[color=red]-[/color] [color=blue]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
        Citizen: '[color=red]-[/color] [color=blue]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
        Member: '[color=red]-[/color] [color=blue]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
        New: '[color=red]-[/color] [color=lightpurple]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
        Guest: '[color=red]-[/color] [color=lightpurple]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
        Vip1: '[color=red]-[/color] [color=gold]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
        Vip2: '[color=red]-[/color] [color=gold]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
        Vip3: '[color=red]-[/color] [color=gold]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
        Funder: '[color=red]-[/color] [color=gold]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
        Founder: '[color=red]-[/color] [color=yellow]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
        RetiredAdmin: '[color=red]-[/color] [color=gold]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
        RetiredArchitect: '[color=red]-[/color] [color=gold]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
        RetiredMod: '[color=red]-[/color] [color=gold]%PLAYER_NAME%[/color] [color=gray]has left the %SERVER_NAME% server.[/color]'
    players:
        Neylion: '[color=red]-[/color] [color=red]%PLAYER_NAME%[/color] [color=gray]left the %SERVER_NAME% server. Play nice! ~[/color]'
        Kyralix: '[color=red]-[/color] [color=gold]%PLAYER_NAME%[/color] [color=gray]the cool kid just left the %SERVER_NAME% server! Aww ~[/color]'
        Hawooo: '[color=red]-[/color] [color=red]%PLAYER_NAME%[/color] [color=gray]left the %SERVER_NAME% server. Or so you think...[/color]'
        Robot_Rebel: '[color=red]-[/color] [color=darkgreen]%PLAYER_NAME%[/color] [color=gray]left the %SERVER_NAME% server. Goodbye, baes! [/color]'