eithon:
  UseMarkUpForMessages: 0
  UseWrappingForMessages: 0
  
  #
  # Debug level
  #  0 = NONE (no debug messages)
  #  1 = MAJOR (only major messages)
  #  2 = MINOR (also minor messages)
  #  3 = VERBOSE (all messages)
  #
  DebugLevel: 1


database:
  Name: TST_e_bungee
  Hostname: mc.eithon.net
  Port: 3306
  Username: TST_e_bungee
  Password: 4eu2yDNLWBJf8LqE

# PRD
#  Name: eithon_stats
#  Username: eithon_stats
#  Password: xxx

# TST
#  Name: TST_e_bungee
#  Username: TST_e_bungee
#  Password: 4eu2yDNLWBJf8LqE

# DEV
#  Name: DEV_e_bungee
#  Username: DEV_e_bungee
#  Password: NnqGGK9Mcr328Mby

commands:

messages:
	#
	# Parameters: <player name> (%s)
	#
	RequestTpTo: 'Player %s requests to teleport to you. Enter one of the commands "/eithonbungee tp accept" or "/eithonbungee tp deny".'
	
	#
	# Parameters: <player name> (%s)
	#
	RequestTpHere: 'Player %s requests to teleport you to him/her. Enter one of the commands "/eithonbungee tp accept" or "/eithonbungee tp deny".'
	
	#
	# Parameters: <player name> (%s)
	#
	DenyTpTo: 'Player %s denied you to teleport to him/her.'
	
	#
	# Parameters: <player name> (%s)
	#
	DenyTpHere: 'Player %s denied to be teleported to you.'
	
