eithon:
  UseMarkUpForMessages: 0
  UseWrappingForMessages: 0
  
  #
  # Debug level
  #  0 = NONE (no debug messages)
  #  1 = MAJOR (only major messages)
  #  2 = MINOR (also minor messages)
  #  3 = VERBOSE (all messages)
  #
  DebugLevel: 3

MaxAllowedTeleportDelayTimeSpan: 30
MaxAllowedMessageDelayInSeconds: 10

GroupPriorities: [Owner, Admin, Developer, Architect, Designer, Mod, Submod, Tourist, Trusted, Vip1, Vip2, Vip3, Builder, Legendary, Veteran, Citizen, Member, New, Funder, Founder, RetiredAdmin, RetiredArchitect, RetiredMod]

database:
  Name: eithon_bungee
  Hostname: localhost
  Port: 3306
  Username: eithon_plugin
  Password: 94SnHAGP3RV0mESN

# TST
#  Name: TST_e_bungee
#  Hostname: rookgard.eithon.net
#  Username: TST_e_plugin
#  Password: bWfRHZsAy42RdFBJ

# DEV
#  Name: DEV_e_bungee
#  Hostname: rookgard.eithon.net
#  Username: DEV_e_plugin
#  Password: J5FE9EFCD1GX8tjg

commands:

messages:
  #
  # Parameters: <player name> (%s)
  #
  RequestTpTo: 'Player %s requests to teleport to you. Enter one of the commands "/eithonbungee tp accept" or "/eithonbungee tp deny".'
  
  #
  # Parameters: <player name> (%s)
  #
  RequestTpHere: 'Player %s requests to teleport you to him/her. Enter one of the commands "/eithonbungee tp accept" or "/eithonbungee tp deny".'
  
  #
  # Parameters: <player name> (%s)
  #
  DenyTpTo: 'Player %s denied you to teleport to him/her.'
  
  #
  # Parameters: <player name> (%s)
  #
  DenyTpHere: 'Player %s denied to be teleported to you.'
  
  #
  # Parameters: <player name> (%s), <message> (%s)
  #
  MessageSent: 'To %s: %s'
  
  #
  # Parameters: <player name> (%s), <message> (%s)
  #
  MessageFrom: 'From %s: %s'
  
  #
  # Parameters: <name> (%s)
  #
  WarpAdded: 'Warp location %s has been added.'

  #
  # Parameters: <server name> (%s)
  AlreadyConnectedToServer: You are already connected to server %s.

  #
  # Parameters: <server name> (%s), <error message> (%s)
  CouldNotConnectToServer: "Could not connect to server %s: %s"

  #
  # Parameters: <server name> (%s)
  ConnectedToServer: Connected to server %s.
  
