name: EithonBungee
main: net.eithon.plugin.bungee.Plugin
version: 0.6
author: vanbrayne
description: A Minecraft plugin for bungee server support
depend: [EithonLibrary]
commands:
  eithonbungee:
    description: Teleport to other player
    usage: /eithonbungee tp | tpa | tphere | message | reply | warp | server
    permission-message: You don't have <permission>
permissions:
  eithonbungee.*:
    description: Gives access to all eithonbungee commands
    default: op
    eithonbungee.tp.*: true
    eithonbungee.tpa.*: true
    eithonbungee.tphere.*: true
    eithonbungee.reply.*: true
    eithonbungee.message.*: true
    eithonbungee.warp.*: true
    eithonbungee.server: true
    eithonbungee.access.server.*: true
  eithonbungee.tp.*:
    description: Access to /eithonbungee tp command
    default: op
  eithonbungee.tpa.*:
    description: Access to /eithonbungee tpa command
    default: op
  eithonbungee.tphere.*:
    description: Access to /eithonbungee tphere command
    default: op
  eithonbungee.message.*:
    description: Access to /eithonbungee message command
    default: op
  eithonbungee.reply.*:
    description: Access to /eithonbungee reply command
    default: op
  eithonbungee.warp.add.*:
    description: Access to /eithonbungee warp add command
  eithonbungee.warp.to.*:
    description: Access to /eithonbungee warp to command
    default: op
  eithonbungee.server:
    description: Access to /eithonbungee server command
    default: op
  eithonbungee.access.server.*:
    description: Access to the different servers
    default: op
  